### ISSUE TITLE
'Favorites' label - visibility

### ISSUE THREAD

**Issue by MetroidFusion** [JCR64/GarlicOS-MinUIfied#1]
Hi

Let me start by saying that I really enjoy this theme. I would like to know if its possible to have the 'Favorites' label visible in the top left corner when entering the favorites section? Like when you enter different consoles sections and the labels 'GB', 'FC', 'PS' etc. are visible.

I have tried editing the English.json file in the lang folder, and that actually made the 'Favorites' label visible. Unfortunately, it comes with the side effect that the text 'Favorites' is also visible in the main menu; in front of/colliding with the menu icons.

Hope you might be able to help me :)

/M

**Comment by JCR64** [comment]
Not possible with GarlicOS currently, sorry! The labels in the Main Menu seem to be the last things to be 'printed' so there is no way to hide them without using the font/language file to obscure it.

Hopefully there will be more freedom in GarlicOS 2.0 theme settings that would allow this.
